#ifndef SAY_HELLO_H
#define SAY_HELLO_H

/*
 * Cross-Platform definitions generated by autotools
 */
#if HAVE_CONFIG_H
#  include <config.h>
#endif /* HAVE_CONFIG_H */

void say_hello(void);

#endif

